:imagesdir: ./images
:toc: macro

= Beginning Robotics with Arduino

== License

The materials for this document are licensed under the Apache license. See the file LICENSE for details.

Copyright 2016 L Dickenson & F Douthit

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
http://www.apache.org/licenses/LICENSE-2.0.

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

toc::[]

== Overview
Robots rely on micro controllers to gather information about and interact with their environment.


== Class 1 Microcontroller Overview
 * Basic Electricity
 * Examples of 
 * Programming microcontrollers
 * Arduino IDE

== Class 2


== Class 3
