:imagesdir: ./images
:toc: macro

= Intro to Real Time Clock (RTC) and Raspberry Pi and Arduino

== License

The materials for this document are licensed under the Apache license. See the file LICENSE for details.

Copyright 2016 F Douthit

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
http://www.apache.org/licenses/LICENSE-2.0.

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

toc::[]


== Overview

A distance sensor 

[NOTE]
In particular, single board hobby PCs like the Raspberry Pi and Arduino do not include a real time clock. For some applications this is OK. Some features require the current time, such as networking.


== Materials and Tools

=== Materials

* link:https://www.pololu.com/product/2474/[Pololu Carrier with Sharp GP2Y0A60SZLF Analog Distance Sensor 10-150cm, 5V]

* Bread Board and Jumper Wires

* Controler
** Arduino Uno or 
** 
** Raspberry Pi 2 or 3

* 32GB SDCard of Raspberry Pi 2 image.

=== Tools



== Datasheet
A data sheet, for our purposes here, documents in a concise manner the features and capabilities of a component.

This is link:DataSheet/Sharp/gp2y0a60szxf_e.pdf[the Datasheet for the GP2Y0A60SZLF].


== Concepts
    


== Arduino
=== Wiring The Electronics
=== Software
=== Testing



== Raspberry Pi
=== Wiring The Electronics
=== Software
=== Testing



== Reference

- link:https://rtc.codeplex.com/SourceControl/latest[DS3231 RTC coding examples]